version: '2'
services:
  db:
    image: postgres:10-alpine
    env_file: .env
    restart: always
    environment:
      - POSTGRES_HOST=db
    volumes:
      - ./db/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  s3:
    image: minio/minio:latest
    command: "server /data"
    environment:
      - MINIO_ACCESS_KEY=DUMMY_ACCESS_KEY
      - MINIO_SECRET_KEY=DUMMY_SECRET_KEY
    ports:
      - "9000:9000"
    volumes:
      - ./db/s3/data:/data
      - ./db/s3/config:/root/.minio
