version: '2'
services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfiles/app/Dockerfile
    command:
      npm run serve
    ports:
      - "3000:3000"
    env_file: .env
    environment:
      - POSTGRES_HOST=db
      - REDIS_HOST=redis
      - NODE_ENV=production
      - DATABASE_URL=postgres://postgres:password@db:5432/blog-js-development
      - IFRAMELY_ENDPOINT=http://iframely:8061
    volumes:
      - ./Dockerfiles/iframely/config.local.js:/iframely/config.local.js
    links:
      - iframely
      - db
      - redis

  redis:
    image: redis:3.2.8
    command: >
      --appendonly yes
      --requirepass password
    env_file: .env
    ports:
      - "6379:6379"
    volumes:
      - ./db/redis:/data

  iframely:
    build:
      context: ./Dockerfiles/iframely
      dockerfile: ./Dockerfile
    ports:
      - "8061:8061"
    env_file: .env
    environment:
      - REDIS_HOST=redis
    volumes:
      - ./Dockerfiles/iframely/config.local.js:/iframely/config.local.js
    links:
      - redis

  db:
    image: postgres:10-alpine
    env_file: .env
    restart: always
    environment:
      - POSTGRES_HOST=db
    volumes:
      - ./db/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  s3:
    image: minio/minio:latest
    command: "server /data"
    environment:
      - MINIO_ACCESS_KEY=DUMMY_ACCESS_KEY
      - MINIO_SECRET_KEY=DUMMY_SECRET_KEY
    ports:
      - "9000:9000"
    volumes:
      - ./db/s3/data:/data
      - ./db/s3/config:/root/.minio
