// load .env first.
require('dotenv').config()

const {
  POSTGRES_USER,
  POSTGRES_PASSWORD,
  POSTGRES_DB,
  S3_BUCKET,
  S3_ENDPOINT,
  DATABASE_URL,
  NODE_ENV,
  AUTH0_API_IDENTIFIER,
  AUTH0_AUDIENCE,
  AWS_ACCESS_KEY_ID,
  AWS_SECRET_ACCESS_KEY
} = process.env

export {
  POSTGRES_USER,
  POSTGRES_PASSWORD,
  POSTGRES_DB,
  S3_BUCKET,
  S3_ENDPOINT,
  DATABASE_URL,
  NODE_ENV,
  AUTH0_API_IDENTIFIER,
  AUTH0_AUDIENCE,
  AWS_ACCESS_KEY_ID,
  AWS_SECRET_ACCESS_KEY
}

export default {
  POSTGRES_USER,
  POSTGRES_PASSWORD,
  POSTGRES_DB,
  S3_BUCKET,
  S3_ENDPOINT,
  DATABASE_URL,
  NODE_ENV,
  AUTH0_API_IDENTIFIER,
  AUTH0_AUDIENCE,
  AWS_ACCESS_KEY_ID,
  AWS_SECRET_ACCESS_KEY
}
