// load .env first.
require('dotenv').config()

const {
  POSTGRES_USER,
  POSTGRES_PASSWORD,
  POSTGRES_DB,
  S3_BUCKET,
  DATABASE_URL,
  NODE_ENV,
  AUTH0_API_IDENTIFIER,
  AUTH0_AUDIENCE
} = process.env

export {
  POSTGRES_USER,
  POSTGRES_PASSWORD,
  POSTGRES_DB,
  S3_BUCKET,
  DATABASE_URL,
  NODE_ENV,
  AUTH0_API_IDENTIFIER,
  AUTH0_AUDIENCE
}

export default {
  POSTGRES_USER,
  POSTGRES_PASSWORD,
  POSTGRES_DB,
  S3_BUCKET,
  DATABASE_URL,
  NODE_ENV,
  AUTH0_API_IDENTIFIER,
  AUTH0_AUDIENCE
}
